apiVersion: 1

contactPoints:
  - orgId: 1
    name: pipeline-oncall
    receivers:
      - uid: pipeline-oncall-email
        type: email
        settings:
          addresses: oncall@pipeline.local
          singleEmail: true
        disableResolveMessage: false
